# Generated by Django 4.0.6 on 2022-07-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_articlemodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='qisqa_mazmun',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='sarlavha',
            field=models.CharField(max_length=50),
        ),
    ]
