# Generated by Django 4.0.6 on 2022-07-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shahar',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
